datasource:
  goods:
    # 注意！！！很重要：url末尾要加上  &pinGlobalTxToPhysicalConnection=true，否则会报执行错误
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&pinGlobalTxToPhysicalConnection=true
    user: test
    password: 123456
    minimum-idle: 1
    maximum-pool-size: 3
  history:
    url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&pinGlobalTxToPhysicalConnection=true
    user: test
    password: 123456
    minimum-idle: 1
    maximum-pool-size: 3
spring:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate.transaction.jta.platform: priv.transaction.test.config.AtomikosJtaPlatform
      javax.persistence.transactionType: JTA
